include: 'https://gitlab.gnome.org/GNOME/citemplates/raw/master/flatpak/flatpak_ci_initiative.yml'

stages:
  - test
  - deploy

variables:
    BUNDLE: "color-picker-nightly.flatpak"
    MANIFEST_PATH: "org.gnome.design.ColorPicker.json"
    FLATPAK_MODULE: "color-picker"

flatpak:
  extends: '.flatpak'
  image: "registry.gitlab.gnome.org/gnome/gnome-runtime-images/rust_bundle:master"
  variables:
    RUNTIME_REPO: 'https://nightly.gnome.org/gnome-nightly.flatpakrepo'
    APP_ID: "org.gnome.design.ColorPicker"
